language: python

python:
- "3.6.4" 

services:
- postgresql

env:
  global:
    -APP_SETTINGS = 'testing'

install:
- pip install -r requirements.txt
- pip install pytest-cov

before_script:
- "psql -c 'create database test_ireporterdb;' -U postgres"

script:
- python -m pytest restapi/tests --cov
- coverage report

after_success:
- coveralls

