language: python

python:
- "3.6.4" 

services:
- postgresql

env:
  global:
    -DB_NAME=test_ireporterdb

before_script:
- "psql -c 'create database test_ireporterdb;' -U postgres"

install:
- pip install -r requirements.txt

script:
- python -m pytest restapi/tests --cov
- coverage

after_success:
- coveralls

