language: python

python:
  - "3.6" 

services:
  - postgresql

env:
  global:
    - DB_NAME='testdb'

install:
  - pip install -r requirements.txt
  - pip install pytest-cov

before_script:
  - "psql -c 'create database testdb;' -U postgres"

script:
  - pytest --cov
  - coverage report

after_success:
  - coveralls

