language: python

python:
- "3.6.4" 

services:
- postgresql

before_script:
- "psql -c 'create database ireporter;' -U postgres"

install:
- pip install -r requirements.txt

script:
- python -m pytest restapi/tests --cov
- coverage

after_success:
- coveralls

